controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

module_controllers:
    resource:
        path: ../src/Module
        # or more specific: ../src/Module/*
        namespace: App\Module
    type: attribute